version: '2'
services:

    killianbrackey.com:
        ports:
            -   "80:80"
    developer:
        image: zzrot/lazycat
        container_name: dev
        volumes:
            -   ./killianbrackey.com:/usr/src/app:rw
        working_dir: /usr/src/app
        ports:
            -   "3000:3000"
            -   "3001:3001"
        networks:
            - frontend

    calc.killianbrackey.com:
        ports:
            - "81:3000"
