version: '2'
services:
    proxy:
        image: zzrot/alpine-caddy
        ports:
            -   "80:80"
            -   "443:443"
        volumes:
            -   ./compose/proxy/Caddyfile:/etc/Caddyfile
            -   ./.caddy:/root/.caddy
        networks:
            - frontend

    killianbrackey.com:
        expose:
            -   80

    calc.killianbrackey.com:
       expose:
            -   3000
